In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as pyplot
%matplotlib inline

In [ ]:
from google.colab import files
uploaded=files.upload()


Saving insurance_data (1).csv to insurance_data (1) (1).csv


In [ ]:
df=pd.read_csv(list(uploaded.keys())[0])

In [ ]:
df

age  affordibility  bought_insurance
0    22              1                 0
1    25              0                 0
2    47              1                 1
3    52              0                 0
4    46              1                 1
5    56              1                 1
6    55              0                 0
7    60              0                 1
8    62              1                 1
9    61              1                 1
10   18              1                 0
11   28              1                 0
12   27              0                 0
13   29              0                 0
14   49              1                 1
15   55              1                 1
16   25              0                 1
17   58              1                 1
18   19              0                 0
19   18              1                 0
20   21              1                 0
21   26              0                 0
22   40              1                 1
23   45              1                 1
24   50              1                 1
25   54              1                 1
26   23              1                 0
27   46              1                 0

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, Y_train, Y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,train_size=0.8)

In [ ]:
X_train

age  affordibility
2    47              1
26   23              1
1    25              0
0    22              1
4    46              1
7    60              0
16   25              0
24   50              1
8    62              1
13   29              0
23   45              1
12   27              0
5    56              1
18   19              0
10   18              1
21   26              0
19   18              1
9    61              1
15   55              1
11   28              1
14   49              1
20   21              1

In [ ]:
X_test

age  affordibility
27   46              1
6    55              0
25   54              1
17   58              1
3    52              0
22   40              1

In [ ]:
Y_train

2     1
26    0
1     0
0     0
4     1
7     1
16    1
24    1
8     1
13    0
23    1
12    0
5     1
18    0
10    0
21    0
19    0
9     1
15    1
11    0
14    1
20    0
Name: bought_insurance, dtype: int64

In [ ]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100
X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [ ]:
model=keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
    ])
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])
model.fit(X_train_scaled,Y_train,epochs=500)


Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 0.7175
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - accuracy: 0.5000 - loss: 0.7171
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7167
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.7163
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.7159
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - accuracy: 0.5000 - loss: 0.7155
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7151
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.7147
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.5000 - loss: 0.7143
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.5000 - loss: 0.7140
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.7136
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.5000 - loss

In [ ]:
model.evaluate(X_train_scaled,Y_train)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 156ms/step - accuracy: 0.6818 - loss: 0.6136


[0.6136358380317688, 0.6818181872367859]

In [ ]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step


array([[0.6773523 ],
       [0.5549539 ],
       [0.6971236 ],
       [0.70674795],
       [0.54641706],
       [0.66209066]], dtype=float32)

In [ ]:
Y_test

27    0
6     0
25    1
17    1
3     0
22    1
Name: bought_insurance, dtype: int64

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [ ]:
model.fit(X_train, Y_train)

LogisticRegression()

In [ ]:
model.predict(X_test)

array([1, 1, 1, 1, 1, 1])

In [ ]:
model.score(X_test,Y_test)

0.5

In [ ]:
model.predict_proba(X_test)

array([[2.08038107e-02, 9.79196189e-01],
       [1.14799497e-03, 9.98852005e-01],
       [1.93469510e-03, 9.98065305e-01],
       [5.85180108e-04, 9.99414820e-01],
       [2.81285835e-03, 9.97187142e-01],
       [1.13458480e-01, 8.86541520e-01]])

In [ ]:
model.coef_

array([[ 0.29928414, -0.2234366 ]])